StartupEvents.registry('block', e => {
    e.create("charcoal_block")
        .displayName("Block of charcoal")
        .soundType("stone")
        .mapColor('grey')
        .hardness(5)
        .resistance(1.0)
        .requiresTool(true)
        .tagBlock("forge:blocks/charcoal")
        .tagBlock("minecraft:mineable/pickaxe")
})