StartupEvents.registry('item', e => {
    e.create('elysium_sword_op', 'sword')
        .displayName('Elysium Sword')
        .tooltip('A sword made of Elysium')
        .unstackable()
        .rarity('rare')
        .tier('elysium_tier')
        .texture('kubejs:item/elysium_sword')

    e.create('cosmic_sword', 'sword')
        .displayName('Cosmic Sword')
        .tooltip('A sword made of Cosmic Energy')
        .unstackable()
        .rarity('epic')
        .tier('cosmic_tier')
        .texture('kubejs:item/cosmic_sword/layer_0').texture('kubejs:item/cosmic_sword/layer_1').texture('kubejs:item/cosmic_sword/mask')
})